version: "3"

  services:
    client:
      image: kelwinsj/client-new:latest
      container_name: client-yolo
      stdin_open: true
      tty: true
      ports:
        - "3000:3000"
      volumes:
        - ./client:/app
      networks:
        - yolo-network
      depends_on:
        - backend

    backend:
      image: kelwinsj/node-back:latest
      container_name: client-backend
      ports:
        - "5000:5000"
      volumes:
        - ./backend:/app
      environment:
        - MONGODB_URI = ${MONGODB}
      networks:
        - yolo-network


  volumes:
    data:


  networks:
    yolo-network:
      driver: bridge