version: "3.8"

services:
  client:
    build:
      context: ./client 
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "3000:3000"
    networks:
      - network_bridge
    image: kelwinsj/client-new:latest

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - network_bridge
    image: kelwinsj/node-back:latest

  database:
    image: mongo:latest
    container_name: database
    environment:
      - MONGODB_URI=${MONGO_DB}
    ports:
      - "27017:27017"

    networks:
      - network_bridge

networks:
  network_bridge:
    driver: bridge