apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: kelwinsj/node-back:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "900m"
        ports:
        - containerPort: 5000
        env:
             - name: MONGODB_URI
               valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_URI